### PR TITLE
Update to ddclient v3.9.0

### LINKED ISSUE #9: Development branch / IPv6 Support
This is the only output I get from the docker console after 1 hour:

```
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/

-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1004
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
Setting up watches.
Watches established.
[services.d] done.
```

### LINKED ISSUE #11: ddclient no ip found but works via command line
Hi,

I'm running Ubuntu 18.04 and ddclient within a docker container. I've configured my ddclient.conf however, when running from the daemon I get the following error:

ddclient         | 2018-08-08T08:56:21.253119508Z WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''

However, if I run:

ddclient -file=/config/ddclient.conf -daemon=0 -debug -verbose -noquiet

from within the container then the IP is found and updated.

My docker compose yml for the container is:

  ddclient:
    image: "linuxserver/ddclient"
    container_name: "ddclient"
    volumes:
      - ${USERDIR}/docker/ddclient:/config
    restart: always
    environment:
      - PUID=xxxx
      - PGID=xxx
      - TZ=${TZ}

Any ideas on how to correct this?

### LINKED ISSUE #12: Cloudflare API v1 End of Life on November 9th, 2016
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

Due to the [deprecation of the v1 Cloudflare API](https://blog.cloudflare.com/sunsetting-api-v1-in-favor-of-cloudflares-current-client-api-api-v4/) the current version of ddclient cannot update any Cloudflare based hosts.

There is a fix for this in the [upstream github repo](https://github.com/ddclient/ddclient/pull/42) however since then no new releases have been tagged/made.

Could we update the container to utilise the upstream code instead of the release on sourceforce?
Seems they're both maintained by wimpunk, however the upstream GitHub repo is maintained actively.

Happy to submit a PR if this will be considered as an option.

### PR DESCRIPTION
**Pull request by nightah**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

This updates the version of ddclient from v3.8.3 to v3.9.0.
closes #9 
closes #11 
closes #12.

### CODE REVIEW

**Comment by nightah** [comment]
Can do shortly.

**Comment by CHBMB** [comment]
Thanks for this PR @nightah

**Comment by sparklyballs** [comment]
what's the source for the changes to the config ? 

is it in the new version or something whipped up by yourself ?

**Comment by nightah** [comment]
It's all based on the default provided upstream.
Because the Cloudflare v4 API isn't found at `www.cloudflare.com` it is instead `api.cloudflare.com/client/v4` having it within your config will cause it to attempt the deprecated v1 API.
https://github.com/ddclient/ddclient/blob/02c983a991531f5bb1637701b9d0c399094bba29/ddclient#L443-L444 for reference.

**Comment by tobbenb** [comment]
Thank you @nightah :)

Jenkins test this please

**Pull request merged**
