### PR TITLE
arm64 base image source, in separate dockerfile

### PR DESCRIPTION
**Pull request by seffyroff**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
This PR renames the Dockerfile which is not acceptable.

Plus, we create separate repos for armhf and arm64 images

**Comment by seffyroff** [comment]
OK, shall I PR to a different repo?  I didn't want to just overwrite the Dockerfile with the arm64 bin source..

There's a manifest process to include multiarch in a single Dockerfile, but it seems complicated..

**Comment by aptalca** [comment]
Yeah, we looked into the manifest a little while back and decided against it. I'll bring it up with the rest of the team and see if there is a technical issue holding us back from releasing this for armhf and arm64. It could be that we didn't get around to it yet. If so, we'll bump it up on the list

**Comment by tobbenb** [comment]
It was probably me being lazy :p
Most likely I just forgot about arm.

**Pull request closed without merging**
