### PR TITLE
fix: intendation for long PID config line

### PR DESCRIPTION
**Pull request by rugk**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-ddclient/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Keeps the comments in order.

## Benefits of this PR and context:

Not really a typo fix, but it’s visually nice.

## How Has This Been Tested?

no

### CODE REVIEW

**Comment by rugk** [comment]
Could anyone handle this PR? It's really just a style fix…

**Comment by Roxedus** [comment]
Might aswell line up all the comments in that section if this PR really is about the overall style

**Comment by rugk** [comment]
Oh only looked at the active (not commented out) comments/code. I guess, comments at the beginning could change how the indentation is shown if these are removed, though if one uses tabs that should usually not be a big problem.

**Comment by Roxedus** [comment]
I just looked at this with the raw view and they line up, but not in any other editor I have. There's just no way to win this fight with tabs, I will however let the rawview decide.

**Pull request merged**
